import type { FilamentChannel, PrinterProfile } from '../types';

export const DEFAULT_FILAMENTS: FilamentChannel[] = [
  {
    id: 1,
    name: 'Anycubic Pure White',
    color: '#F8FAFC',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 1.0,
    spoolGramsRemaining: 850,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-001',
  },
  {
    id: 2,
    name: 'Anycubic Glacier Cyan',
    color: '#06B6D4',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 0.95,
    spoolGramsRemaining: 920,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-002',
  },
  {
    id: 3,
    name: 'Anycubic Obsidian Black',
    color: '#1E293B',
    material: 'High-Speed PLA',
    tempNozzle: 220,
    tempBed: 60,
    purgeFactor: 1.15,
    spoolGramsRemaining: 740,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-003',
  },
  {
    id: 4,
    name: 'Anycubic Coral Orange',
    color: '#F97316',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 1.0,
    spoolGramsRemaining: 680,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-004',
  },
  {
    id: 5,
    name: 'Anycubic Silk Gold',
    color: '#EAB308',
    material: 'High-Speed PLA',
    tempNozzle: 210,
    tempBed: 60,
    purgeFactor: 1.05,
    spoolGramsRemaining: 550,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-005',
  },
  {
    id: 6,
    name: 'Anycubic Forest Emerald',
    color: '#10B981',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 0.95,
    spoolGramsRemaining: 810,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-006',
  },
  {
    id: 7,
    name: 'Anycubic Crimson Ruby',
    color: '#EF4444',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 1.05,
    spoolGramsRemaining: 600,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-007',
  },
  {
    id: 8,
    name: 'Anycubic Tech Slate',
    color: '#64748B',
    material: 'High-Speed PLA',
    tempNozzle: 215,
    tempBed: 60,
    purgeFactor: 0.9,
    spoolGramsRemaining: 950,
    slotActive: true,
    rfidTag: 'ANYC-RFID-PLA-008',
  },
];

export const PRINTER_PROFILES: Record<string, PrinterProfile> = {
  kobra3: {
    id: 'kobra3',
    name: 'Anycubic Kobra 3 Combo',
    tagline: 'Multi-Color Flagship (up to 8 colors with dual ACE Pro)',
    bedX: 250,
    bedY: 250,
    bedZ: 260,
    maxColors: 8,
    aceProUnits: 2,
    maxSpeed: 600,
    maxAcceleration: 20000,
    nozzleDiameter: 0.4,
    wipeTower: {
      x: 195,
      y: 195,
      width: 32,
      minVolume: 120,
      enabled: true,
    },
  },
  kobra_x: {
    id: 'kobra_x',
    name: 'Anycubic Kobra X / Max Series',
    tagline: 'Large Format Multi-Material Platform',
    bedX: 300,
    bedY: 300,
    bedZ: 350,
    maxColors: 8,
    aceProUnits: 2,
    maxSpeed: 500,
    maxAcceleration: 12000,
    nozzleDiameter: 0.4,
    wipeTower: {
      x: 240,
      y: 240,
      width: 35,
      minVolume: 140,
      enabled: true,
    },
  },
};
